//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// ToolBasic00.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ToolBasic00TYPE             130
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDD_MENUFORMVIEW                310
#define IDD_TERRAIN_TAB                 313
#define IDB_TERRAIN1                    326
#define IDB_TERRAIN2                    331
#define IDB_TERRAIN3                    332
#define IDB_TERRAIN4                    333
#define IDB_TERRAIN5                    334
#define IDD_TEXTURE_TAB                 335
#define IDD_OBJECT_TAB                  337
#define IDD_WATER_TAB                   339
#define ID_TERRAIN1_RAD                 1006
#define ID_TERRAIN3_RAD                 1008
#define IDC_SETTYPE_GRO                 1008
#define ID_TERRAIN4_RAD                 1009
#define IDC_POWER_GRO                   1015
#define IDC_POWER_SLI                   1016
#define IDC_BRUSH_SIZE_GRO              1019
#define IDC_BRUSH_SIZE_SLI              1020
#define IDC_POWER_EDI                   1021
#define IDC_POWER_SPI                   1023
#define IDC_EDIT_HEIGHT_GRO             1028
#define IDC_EDIT_HEIGHT_SLI             1030
#define IDC_EDIT_HEIGHT_EDI             1031
#define IDC_EDIT_HEIGHT_SPI             1032
#define IDD_CREATEMAP_VIEW              1033
#define ID_MAP_SIZE_COM                 1034
#define ID_MAP_SIZE_TEXT                1035
#define ID_DEFAULT_HEIGHT_SLI           1036
#define ID_DEFAULT_HEIGHT_TEXT          1037
#define ID_DEFAULT_HEIGHT_SPI           1038
#define ID_MAP_SIZE_GRO                 1039
#define ID_DEAULT_HEIGHT_GRO            1040
#define ID_DEFAULT_HEIGHT_EDI           1041
#define ID_DEF_TEXTURE_GRO              1042
#define ID_TERRAIN2_RAD                 1043
#define ID_TERRAIN5_RAD                 1044
#define ID_TERRAIN1_PIC                 1045
#define ID_TERRAIN2_PIC                 1046
#define ID_TERRAIN3_PIC                 1047
#define ID_TERRAIN4_PIC                 1048
#define ID_TERRAIN5_PIC                 1049
#define ID_CREATE_MAP_BNT               1050
#define IDC_MAPTOOL_TAB                 1051
#define IDC_SELECT_TEXTURE_GRO          1052
#define IDC_TEXTURE_DENSITY_GRO         1053
#define IDC_TEXTURE_DENSITY_SLI         1054
#define IDC_TEXTURE_DENSITY_EDI         1055
#define IDC_TEXTURE_DENSITY_SPI         1056
#define IDC_BRUSH_DENSITY_SIZE_GRO      1057
#define IDC_BRUSH_DENSITY_SIZE_SLI      1058
#define IDC_BRUSH_DENSITY_SIZE_EDI      1059
#define IDC_BRUSH_DENSITY_SIZE_SPI      1060
#define IDC_OBJECT_FILE_TRE             1061
#define IDC_BRUSH_DENSITY_GRO           1061
#define IDC_BRUSH_DENSITY_SLI           1062
#define IDC_OBJECT_LIST_LIS             1063
#define IDC_BRUSH_DENSITY_EDI           1063
#define IDC_OBJECT_FILE_TEXT            1064
#define IDC_BRUSH_DENSITY_SPI           1064
#define IDC_OBJECT_LIST_TEXT            1065
#define IDC_Tex2_Density_GRO            1065
#define IDC_OBJECT_SIZE_GRO             1066
#define IDC_TEX2_DSIZE_SLI              1066
#define IDC_OBJECT_SIZE_SLI             1067
#define IDC_TEX2_DSIZE_EDI              1067
#define IDC_OBJECT_SIZE_EDI             1068
#define IDC_TEX2_DSIZE_SPI              1068
#define IDC_OBJECT_SIZE_SPI             1069
#define IDC_Tex3_Density_GRO            1069
#define IDC_OBJECT_POS_GRO              1070
#define IDC_TEX3_DSIZE_SLI              1070
#define IDC_TEX3_DSIZE_EDI              1071
#define IDC_X_TEXT                      1072
#define IDIDC_TEX3_DSIZE_SPI            1072
#define IDC_OBJECT_ATTRIBUTE_GRO        1073
#define IDC_COLLISION_CHE               1074
#define IDC_WATER_HEIGHT_GRO            1075
#define IDC_WATER_HEIGHT_SLI            1076
#define IDC_WATER_HEIGHT_EDI            1077
#define IDC_Y_TEXT                      1078
#define IDC_WATER_HEIGHT_SPI            1078
#define IDC_WATER_UV_SPEED_GRO          1079
#define IDC_Z_TEXT                      1080
#define IDC_WATER_UV_SPEED_SLI          1080
#define IDC_OBJECT_ROT_GRO              1081
#define IDC_WATER_UV_SPEED_EDI          1081
#define IDC_OBJECT_ROT_X_SLI            1082
#define IDC_WATER_UV_SPEED_SPI          1082
#define IDC_OBJECT_ROT_X_EDI            1083
#define IDC_WATER_HEIGHT_SPEED_GRO      1083
#define IDC_OBJECT_ROT_X_SPI            1084
#define IDC_WATER_HEIGHT_SPEED_SLI      1084
#define IDC_X_TEXT2                     1085
#define IDC_WATER_HEIGHT_SPEED_EDI      1085
#define IDC_OBJECT_ROT_Y_SLI            1086
#define IDC_WATER_HEIGHT_SPEED_SPI      1086
#define IDC_OBJECT_ROT_Y_EDI            1087
#define IDC_WATER_WAVE_HEIGHT_GRO       1087
#define IDC_OBJECT_ROT_Y_SPI            1088
#define IDC_WATER_WAVE_HEIGHT_SLI       1088
#define IDC_Y_TEXT2                     1089
#define IDC_WATER_WAVE_HEIGHT_EDI       1089
#define IDC_OBJECT_ROT_Z_SLI            1090
#define IDC_WATER_WAVE_HEIGHT_SPI       1090
#define IDC_OBJECT_ROT_Z_EDI            1091
#define IDC_WATER_WAVE_FREQUENCY_GRO    1091
#define IDC_OBJECT_ROT_Z_SPI            1092
#define IDC_WATER_WAVE_FREQUENCY_SLI    1092
#define IDC_Z_TEXT2                     1093
#define IDC_WATER_WAVE_FREQUENCY_EDI    1093
#define IDC_DESTRUCTION_CHE             1094
#define IDC_WATER_WAVE_FREQUENCY_SPI    1094
#define IDC_POS_X_TEXT                  1095
#define IDC_WATER_TRANSPARENT_GRO       1095
#define IDC_POS_Y_TEXT                  1096
#define IDC_WATER_TRANSPARENT_SLI       1096
#define IDC_DELETE_BTN                  1097
#define IDC_WATER_TRANSPARENT_EDI       1097
#define IDC_POS_Z_TEXT                  1098
#define IDC_WATER_TRANSPARENT_SPI       1098
#define IDC_DELETE_BTN2                 1099
#define IDC_DUPLCATION_BTN              1099
#define IDC_SHARP_RAD                   1099
#define IDC_WALKABLE_CHE                1100
#define IDC_INCREMENT_EDI               1221
#define IDC_Tex1_Density_GRO            1221
#define IDC_TEX1_DSIZE_SLI              1222
#define IDC_INCREMENT_SPI               1223
#define IDC_SET_BRUSH_GRO               1224
#define IDC_BRUSH_SIZE_EDI              1225
#define IDC_SET_TEX_DENSITY_GRO         1226
#define IDC_TEX1_DSIZE_EDI              1227
#define IDC_FLAT_SIZE_GRO               1228
#define IDC_BRUSH_SIZE_SPI              1229
#define IDC_FLAT_SIZE_SLI               1230
#define IDC_Tex1_DSIZE_SPI              1230
#define IDC_FLAT_SIZE_EDI               1231
#define IDC_FLAT_SIZE_SPI               1232
#define IDC_SMOOTH_RAD                  1398
#define IDC_BRUSH_RAD                   1498
#define IDC_BRUSH_TYPE_GRO              1500
#define IDC_ERASE_RAD                   1501
#define IDC_UP_RAD                      1502
#define IDC_DOWN_RAD                    1503
#define IDC_EDIT_RAD                    1504
#define IDC_RETURN_RAD                  1505
#define IDC_FIXED_RAD                   1506
#define IDC_FLAT_RAD                    1507
#define IDC_TRIM_RAD                    1508
#define IDC_RESET_RAD                   1509
#define IDC_SPRAY_RAD                   1510

#define IDC_OBJECT_FILE_TRE             2001
#define IDC_OBJECT_LIST_LIS             2002
#define IDC_OBJECT_LIST_TEXT            2003
#define IDC_OBJ_FILE_NAME_TEXT          2004
#define IDC_OBJECT_ATTRIBUTE_GRO        2010
#define IDC_COLLISION_CHE               2011
#define IDC_DESTRUCTION_CHE             2012
#define IDC_OBJECT_FILE_TEXT            2013
#define IDC_OBJECT_SIZE_GRO             2020
#define IDC_OBJECT_SIZE_SLI             2021
#define IDC_OBJECT_SIZE_EDI             2022
#define IDC_OBJECT_SIZE_SPI             2023
#define IDC_OBJECT_POS_GRO              2030
#define IDC_X_TEXT                      2031
#define IDC_Y_TEXT                      2032
#define IDC_Z_TEXT                      2033
#define IDC_POS_X_TEXT                  2034
#define IDC_POS_Y_TEXT                  2035
#define IDC_POS_Z_TEXT                  2036
#define IDC_OBJECT_ROT_GRO              2040
#define IDC_X_TEXT2                     2041
#define IDC_Y_TEXT2                     2042
#define IDC_Z_TEXT2                     2043
#define IDC_OBJECT_ROT_X_SLI            2044
#define IDC_OBJECT_ROT_Y_SLI            2045
#define IDC_OBJECT_ROT_Z_SLI            2046
#define IDC_OBJECT_ROT_X_EDI            2047
#define IDC_OBJECT_ROT_Y_EDI            2048
#define IDC_OBJECT_ROT_Z_EDI            2049
#define IDC_OBJECT_ROT_X_SPI            2050
#define IDC_OBJECT_ROT_Y_SPI            2051
#define IDC_OBJECT_ROT_Z_SPI            2052
#define IDC_GROUP_OBJ_CREATE            2069
#define IDC_OBJ_SELECT_BUTTON           2070
#define IDC_DELETE_BTN                  2071
#define IDC_OBJ_FILE_OPEN_BUTTON        2072
#define IDC_OBJ_LOCATE_BUTTON           2073
#define IDC_OBJ_CANCEL_BUTTON           2074
#define IDC_OBJ_RELOCATE_BUTTON         2075
#define IDC_OBJ_REMOVE_BUTTON           2076
#define IDC_BLOCK_GROUP_EDIT_GRO        2080
#define IDC_BLOCK_GROUP_LATEST_DEL_BUTTON 2081
#define IDC_BLOCK_GROUP_END_BUTTON      2082
#define IDC_BLOCK_GROUP_NEW_BUTTON      2083
#define IDC_BLOCK_GROUP_LIST_LIS        2084
#define IDC_BLOCK_GROUP_DELETE_BUTTON   2085
#define IDC_BLOCK_GROUP_TEXT            2086
#define IDC_BLOCK_GROUP_MODIFY_BUTTON   2087
#define IDC_BLOCK_GROUP_CLEAR_BUTTON    2088
#define IDC_BLOCK_GROUP_CLEAR_BUTTON    2088
#define IDC_BUTTON1                     2100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        341
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1100
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
